# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{progenitor}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Paul Hieromnimon"]
  s.date = %q{2011-03-05}
  s.description = %q{Progenitor is a lightweight gem for building factories, especially useful for testing, but
                     there is no reason why it can't be used in application code.  Unlike Factory Girl, Progenitor
                     makes no assumption that products are instances of ActiveRecord::Base - it can be used to produce                     objects of any type.}
  s.email = %q{paul.hieromnimon@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/progenitor/all.rb",
    "lib/progenitor/factory.rb",
    "lib/progenitor/no_such_factory_exception.rb",
    "lib/progenitor/sequence.rb",
    "test/foo.rb",
    "test/foo_factory.rb",
    "test/helper.rb",
    "test/test_no_such_factory_exception.rb",
    "test/test_progenitor.rb",
    "test/test_sequence.rb"
  ]
  s.homepage = %q{http://github.com/pavlos/progenitor}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Extremely lightweight yet full featured factory gem.}
  s.test_files = [
    "test/foo.rb",
    "test/foo_factory.rb",
    "test/helper.rb",
    "test/test_no_such_factory_exception.rb",
    "test/test_progenitor.rb",
    "test/test_sequence.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<test-unit>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<test-unit>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<test-unit>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

